/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OpinieRouteImport } from './routes/opinie'
import { Route as OfertaRouteImport } from './routes/oferta'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as KsefRouteImport } from './routes/ksef'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as FaqKsefRouteImport } from './routes/faq-ksef'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinieRoute = OpinieRouteImport.update({
  id: '/opinie',
  path: '/opinie',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaRoute = OfertaRouteImport.update({
  id: '/oferta',
  path: '/oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const KsefRoute = KsefRouteImport.update({
  id: '/ksef',
  path: '/ksef',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqKsefRoute = FaqKsefRouteImport.update({
  id: '/faq-ksef',
  path: '/faq-ksef',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq-ksef': typeof FaqKsefRoute
  '/kontakt': typeof KontaktRoute
  '/ksef': typeof KsefRoute
  '/o-nas': typeof ONasRoute
  '/oferta': typeof OfertaRoute
  '/opinie': typeof OpinieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq-ksef': typeof FaqKsefRoute
  '/kontakt': typeof KontaktRoute
  '/ksef': typeof KsefRoute
  '/o-nas': typeof ONasRoute
  '/oferta': typeof OfertaRoute
  '/opinie': typeof OpinieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq-ksef': typeof FaqKsefRoute
  '/kontakt': typeof KontaktRoute
  '/ksef': typeof KsefRoute
  '/o-nas': typeof ONasRoute
  '/oferta': typeof OfertaRoute
  '/opinie': typeof OpinieRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq-ksef'
    | '/kontakt'
    | '/ksef'
    | '/o-nas'
    | '/oferta'
    | '/opinie'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq-ksef'
    | '/kontakt'
    | '/ksef'
    | '/o-nas'
    | '/oferta'
    | '/opinie'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/faq-ksef'
    | '/kontakt'
    | '/ksef'
    | '/o-nas'
    | '/oferta'
    | '/opinie'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqKsefRoute: typeof FaqKsefRoute
  KontaktRoute: typeof KontaktRoute
  KsefRoute: typeof KsefRoute
  ONasRoute: typeof ONasRoute
  OfertaRoute: typeof OfertaRoute
  OpinieRoute: typeof OpinieRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinie': {
      id: '/opinie'
      path: '/opinie'
      fullPath: '/opinie'
      preLoaderRoute: typeof OpinieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta': {
      id: '/oferta'
      path: '/oferta'
      fullPath: '/oferta'
      preLoaderRoute: typeof OfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ksef': {
      id: '/ksef'
      path: '/ksef'
      fullPath: '/ksef'
      preLoaderRoute: typeof KsefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq-ksef': {
      id: '/faq-ksef'
      path: '/faq-ksef'
      fullPath: '/faq-ksef'
      preLoaderRoute: typeof FaqKsefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqKsefRoute: FaqKsefRoute,
  KontaktRoute: KontaktRoute,
  KsefRoute: KsefRoute,
  ONasRoute: ONasRoute,
  OfertaRoute: OfertaRoute,
  OpinieRoute: OpinieRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
